alias la='ls -a'
alias ll='ls -al'
alias x='exit'
alias e='emacs -nw'
alias sudoe='sudo emacs -nw'
alias tweet-nowplaying='mpc current | sed -e "s/\(.*\)/#nowplaying \0/" | xargs -0 twitter-friend-list tweet'
